name: options1

args:
  exploration_constant: 2 # Увеличение делает характер алгоаритма более исследовательским, уменьшение - более жадным
  num_searches: 60
  num_iterations: 4
  num_selfPlay_iterations: 500
  num_epochs: 4
  batch_size: 64
  temperature: 1.25 # Увеличение делает характер алгоаритма более исследовательским, уменьшение - более жадным