name: options1

args:
  C: 2
  num_searches: 60
  num_iterations: 2
  num_selfPlay_iterations: 200
  num_epochs: 4
  batch_size: 64
  temperature: 1.25
  dirichlet_epsilon: 0.25
  dirichlet_alpha: 0.3